name: pro_agro
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  get: any
  firebase_auth: any
  firebase_core: any
  cloud_firestore: any
  flutter_svg: ^1.1.6
  lottie: ^2.2.0
  get_storage: ^2.1.1
  persistent_bottom_nav_bar: ^5.0.2
  font_awesome_flutter: ^10.4.0
  flutter_rating_bar: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0
  tab_indicator_styler: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  table_calendar: ^3.0.9
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  adaptive_icon_background: "#2A6049"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#2A6049"
    theme_color: "#2A6049"